version: '3.8'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    restart: always

  broker:
    image: redis:alpine
    volumes:
      - redis_data:/data
    restart: always

  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: web
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - broker
    restart: always

  worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: worker
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
      - broker
    restart: always

  beat:
    build:
      context: .
      dockerfile: Dockerfile
      target: beat
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
      - broker
    restart: always

volumes:
  postgres_data:
  redis_data:
